spring.application.name=BrickGenBackend
spring.config.import=optional:file:.env[.properties]

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.cors.allowed-origin=*

# Spring AI Google GenAI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0

REBRICKABLE_API_KEY=your_rebrickable_api_key_here
